US040 login system
Les-Champignons/lc-kainosjobs-back pull request #4
Opened 2024-12-17 14:01 UTC by dandabs

2024-12-18 13:16 UTC, lukemKainos requested changes

2024-12-18 13:16 UTC, lukemKainos commented on src/main/resources/db/migration/V7__create_user_table.sql
> +    `password` VARCHAR(64) NOT NULL,
just checkeing is this hashed here?

2024-12-18 13:16 UTC, lukemKainos commented on src/main/java/org/kainos/ea/daos/DatabaseConnector.java
> +    }
do we need this?

2024-12-18 13:16 UTC, lukemKainos commented on src/main/java/org/kainos/ea/requests/LoginRequest.java
> +    String password;
encapsulate these

2024-12-18 13:16 UTC, lukemKainos commented on src/main/java/org/kainos/ea/services/AuthService.java
> +    static final int EXPIRATION_TIME = 8 * 60 * 60 * 1000;
is this hardcoded?

2024-12-20 10:35 UTC, dandabs commented on src/main/resources/db/migration/V7__create_user_table.sql
> +    `password` VARCHAR(64) NOT NULL,
yes

2024-12-20 10:35 UTC, dandabs commented on src/main/java/org/kainos/ea/services/AuthService.java
> +    static final int EXPIRATION_TIME = 8 * 60 * 60 * 1000;
yes

2025-01-07 10:49 UTC, lukemKainos commented on src/main/java/org/kainos/ea/services/AuthService.java
> +    static final int EXPIRATION_TIME = 8 * 60 * 60 * 1000;
can you make it not hardcoded?

2025-01-07 10:54 UTC, lukemKainos requested changes

2025-01-07 10:54 UTC, lukemKainos commented on src/main/java/org/kainos/ea/auth/Hasher.java
> +            MessageDigest md = MessageDigest.getInstance("MD5");
can we use SHA instead of MD5? MD5 is broken i believe

2025-01-07 10:54 UTC, lukemKainos commented on src/main/java/org/kainos/ea/auth/Hasher.java
> +            BigInteger no = new BigInteger(1, messageDigest);
number not no pls

2025-01-07 10:54 UTC, lukemKainos commented on src/main/java/org/kainos/ea/services/AuthService.java
> +    static final int EXPIRATION_TIME = 8 * 60 * 60 * 1000;
reraising

2025-01-07 12:31 UTC, lukemKainos approved these changes

2025-01-07 12:33 UTC, CharlotteMKainos approved these changes

2025-01-07 12:33 UTC, merged